language: php
dist: trusty

php:
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
